<a href="https://colab.research.google.com/github/nike-2001/AI-Hands-on/blob/main/Copy_of_Array_Manipulation_and_Padding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy
import numpy as np

## Broadcasting with different dimensions

* Two arrays do not need to have the same number of dimensions to do element-wise operations.
* When the dimensions are not the same, to check the compatibility for broadcasting, start with the trailing dimensions and check the compatibility for each dimension moving towards the left.
* If all the existing dimensions are compatible, then we can do element-wise operations with the two arrays.

```
a      (2d array):  3 x 2
b      (1d array):      2
a + b  (2d array):  3 x 2
```

In [ ]:
a = np.zeros([3,2])
b = np.ones(2)
(a + b).shape

(3, 2)

```
a      (4d array):  3 x 1 x 4 x 2
b      (3d array):      3 x 4 x 2
a + b  (4d array):  3 x 3 x 4 x 2
```

In [ ]:
a = np.zeros([3,1,4,2])
b = np.ones([3,4,2])
(a + b).shape

(3, 3, 4, 2)

# Array Manipulations


## Changing the array shape

### Reshaping


*   `np.reshape(arr, new_shape)`
  * Returns a new array with the shape `new_shape`.
  * The shape of the original array will not change.
  * Might return a **view** of the original array.

In [ ]:
array_1d = np.array([1, 3, 5, 0, 2, 4, 9, 7, 3, 11, 5, 13])

reshaped_array = np.reshape(array_1d, (3, 4))

print("reshaped_array: \n", reshaped_array, "\n")
print("array_1d: \n", array_1d)

reshaped_array: 
 [[ 1  3  5  0]
 [ 2  4  9  7]
 [ 3 11  5 13]] 

array_1d: 
 [ 1  3  5  0  2  4  9  7  3 11  5 13]


**`ndarray.reshape(newshape)`** is equivalent to **`np.reshape()`**

In [ ]:
array_1d = np.array([1, 3, 5, 0, 2, 4, 9, 7, 3, 11, 5, 13])

reshaped_array = array_1d.reshape((4, 3))

print("reshaped_array: \n", reshaped_array, "\n")
print("array_1d: \n", array_1d)

reshaped_array: 
 [[ 1  3  5]
 [ 0  2  4]
 [ 9  7  3]
 [11  5 13]] 

array_1d: 
 [ 1  3  5  0  2  4  9  7  3 11  5 13]


**Using `-1` as a placeholder in the `reshape()` method**

In [ ]:
array_1d = np.array([1, 3, 5, 0, 2, 4, 9, 7, 3, 11, 5, 13])

reshaped_array = array_1d.reshape((4, -1))
print("reshaped array with placeholder: \n", reshaped_array, "\n")

reshaped_array = array_1d.reshape((2, -1, 3))
print("reshaped array with placeholder: \n", reshaped_array, "\n")

reshaped array with placeholder: 
 [[ 1  3  5]
 [ 0  2  4]
 [ 9  7  3]
 [11  5 13]] 

reshaped array with placeholder: 
 [[[ 1  3  5]
  [ 0  2  4]]

 [[ 9  7  3]
  [11  5 13]]] 



In [ ]:
array_2d = np.array([[1,3,5], 
                     [0,2,4]])

print("reshaped to (3,2):\n", array_2d.reshape((3,2)))
print("reshaped to 6:\n", array_2d.reshape(6), "\n")

reshaped to (3,2):
 [[1 3]
 [5 0]
 [2 4]]
reshaped to 6:
 [1 3 5 0 2 4] 



### **`np.ravel(arr)`**

*  Returns a contiguous flattened array (A 1D array, containing the elements of the input array).
*  The shape of the original array will not change.
*  Returns a **view** of the original array. 


In [ ]:
array_2d = np.array([[1,3,5], 
                     [0,2,4]])

raveled_array = np.ravel(array_2d)
raveled_array[0] = -10

print("raveled array: \n", raveled_array, "\n")
print("array_2d: \n", array_2d)

raveled array: 
 [-10   3   5   0   2   4] 

array_2d: 
 [[-10   3   5]
 [  0   2   4]]


**`np.ravel(arr)`** is equivalent to **`np.reshape(arr, -1)` and `arr.ravel()`**

In [ ]:
array_2d = np.array([[1,3,5], 
                     [0,2,4]])

print("raveled array: \n", np.ravel(array_2d), "\n")
print("raveled array alternative: \n", array_2d.ravel(), "\n")
print("reshaped array: \n", np.reshape(array_2d, -1), "\n")

raveled array: 
 [1 3 5 0 2 4] 

raveled array alternative: 
 [1 3 5 0 2 4] 

reshaped array: 
 [1 3 5 0 2 4] 



### **`ndarray.flatten()`**

*  Returns a **copy** of the array flattened to one dimension. 
*  The shape of the original array will not change.

In [ ]:
array_2d = np.array([[1,3,5], 
                     [0,2,4]])

flattened_array = array_2d.flatten()

flattened_array[0] = -10

print("flattened array: \n", flattened_array, "\n")
print("array_2d: \n", array_2d)

flattened array: 
 [-10   3   5   0   2   4] 

array_2d: 
 [[1 3 5]
 [0 2 4]]


### Using **`np.newaxis`**

It is used to increase the dimension of an existing array by one.
* **`nD`** array becomes **`(n+1)D`** array.

It can be used to convert a 1D array to either a row vector or a column vector

In [ ]:
a = np.array([1, 3, 5])

row_vector = a[np.newaxis, :]
row_vector

array([[1, 3, 5]])

In [ ]:
print("row vector alternative:", a[np.newaxis])

row vector alternative: [[1 3 5]]


In [ ]:
print("shape of original array:        ", a.shape)
print("shape of a[np.newaxis, :]", row_vector.shape)

shape of original array:         (3,)
shape of a[np.newaxis, :] (1, 3)


In [ ]:
a = np.array([1, 3, 5])

column_vector = a[:, np.newaxis]
column_vector

array([[1],
       [3],
       [5]])

In [ ]:
print("shape of original array:  ", a.shape)
print("shape of a[:, np.newaxis]:", column_vector.shape)

print("shape of a[:, np.newaxis, np.newaxis]:", a[:, np.newaxis, np.newaxis].shape)
print("shape of a[np.newaxis, :, np.newaxis]:", a[np.newaxis, :, np.newaxis].shape)

shape of original array:   (3,)
shape of a[:, np.newaxis]: (3, 1)
shape of a[:, np.newaxis, np.newaxis]: (3, 1, 1)
shape of a[np.newaxis, :, np.newaxis]: (1, 3, 1)


### **`np.squeeze`**

`np.squeeze(arr, axis)`
* It removes single-dimensional entries from the shape of an array.

In [ ]:
a = np.array([[[1], [3], [5]]])
a.shape

(1, 3, 1)

In [ ]:
np.squeeze(a).shape

(3,)

In [ ]:
a = np.array([[[1], [3], [5]]])
np.squeeze(a, axis=2).shape

(1, 3)

The following code gives an **error** as the size of the selected axis is not equal to one.

In [ ]:
np.squeeze(a, axis=1).shape

AxisError: ignored

When expanded arrays are squeezed, the original array is obtained.

In [ ]:
a = np.array([1, 3, 5])
print("original:", a)

expanded = np.expand_dims(a, axis=0)
print("expanded:", expanded)

squeezed = np.squeeze(expanded, axis=0)
print("squeezed:", squeezed)

original: [1 3 5]
expanded: [[1 3 5]]
squeezed: [1 3 5]


In [ ]:
a = np.array([1, 3, 5])
print("original:", a)

expanded = np.expand_dims(a, axis=1)
print("expanded: \n", expanded)

squeezed = np.squeeze(expanded, axis=1)
print("squeezed:", squeezed)

original: [1 3 5]
expanded: 
 [[1]
 [3]
 [5]]
squeezed: [1 3 5]


## Changing the axes of an array

### **`np.moveaxis`**

`np.moveaxis(arr, original_positions, new_positions)`
* Returns the view of an array with the axes moved from their original positions to the new positions.
* Other axes remain in their original order.

In [ ]:
array_3d = np.ones((2, 3, 4, 5, 6))

axis_moved_array = np.moveaxis(array_3d, [0, 1], [1, 2])
print(axis_moved_array.shape)

(4, 2, 3, 5, 6)


In [ ]:
array_3d = np.array([[[5, 5, 5],
                    [0, 0, 0]],
                     
                    [[1, 2, 3],
                    [-1, -2, -3]],
                     
                    [[6, 7, 8],
                    [-6, -7, -8]]])

print("original array: \n", array_3d, "\n")

moved_axes_array = np.moveaxis(array_3d, 0, 2)
print("array after moving axes: \n", moved_axes_array)

original array: 
 [[[ 5  5  5]
  [ 0  0  0]]

 [[ 1  2  3]
  [-1 -2 -3]]

 [[ 6  7  8]
  [-6 -7 -8]]] 

array after moving axes: 
 [[[ 5  1  6]
  [ 5  2  7]
  [ 5  3  8]]

 [[ 0 -1 -6]
  [ 0 -2 -7]
  [ 0 -3 -8]]]


### **`np.swapaxes`**

`np.swapaxes(arr, axis1, axis2)`
* Returns an array with axis1 and axis2 interchanged.
* Other axes remain in their original order.

In [ ]:
array_3d = np.array([[[5, 5, 5],
                    [0, 0, 0]],
                     
                    [[1, 2, 3],
                    [-1, -2, -3]],
                     
                    [[6, 7, 8],
                    [-6, -7, -8]]])

print("original array: \n", array_3d, "\n")

swapped_axes_array = np.swapaxes(array_3d, 1, 2)
print("array after swapping axes: \n", swapped_axes_array)

original array: 
 [[[ 5  5  5]
  [ 0  0  0]]

 [[ 1  2  3]
  [-1 -2 -3]]

 [[ 6  7  8]
  [-6 -7 -8]]] 

array after swapping axes: 
 [[[ 5  0]
  [ 5  0]
  [ 5  0]]

 [[ 1 -1]
  [ 2 -2]
  [ 3 -3]]

 [[ 6 -6]
  [ 7 -7]
  [ 8 -8]]]


## Splitting an array


*   `np.split(arr, indices_or_sections, axis=0)`
  *   Splits the given array `arr` into multiple sub-arrays along the given `axis` based on `indices_or_sections` and returns a list of sub-arrays.

If `indices_or_sections` is an integer say N, then `arr` will be divided into N equal arrays along the given `axis`.

In [ ]:
array_1d = np.array([1, 7, 11, 0, 3, 17])
split_arrays = np.split(array_1d, 2) 
print(split_arrays)

[array([ 1,  7, 11]), array([ 0,  3, 17])]


If `indices_or_sections` is a list, then `arr` will be split into sub-arrays at the indices mentioned in the list.

In [ ]:
array_1d = np.array([1, 7, 11, 0, 3, 17])

split_arrays = np.split(array_1d, [1]) 
print(split_arrays)

[array([1]), array([ 7, 11,  0,  3, 17])]


Helper function to print splits of an array

In [ ]:
def print_splits(array_to_split):
    for item in array_to_split:
        print(item, "\n")

**Split an array along given axis**

In [ ]:
array_1 = np.array([[1, 7, 11, 12], 
                    [0, 3, 17, 2]])

split_arrays1 = np.split(array_1, 2, axis = 1)
print_splits(split_arrays1)

[[1 7]
 [0 3]] 

[[11 12]
 [17  2]] 



In [ ]:
split_arrays2 = np.split(array_1, [1, 3], axis = 1)
print_splits(split_arrays2)

[[1]
 [0]] 

[[ 7 11]
 [ 3 17]] 

[[12]
 [ 2]] 



### Split - Horizontal


*   `np.hsplit(arr, indices_or_sections)`
  *   Split the given `arr` into multiple sub-arrays horizontally i.e column-wise and returns a list of sub-arrays. 
  *   It is equivalent to split with `axis = 1`.



In [ ]:
array = np.array([1, 2, 3, 4, 5])
split_arrays = np.hsplit(array, [3])
print_splits(split_arrays)

[1 2 3] 

[4 5] 



In [ ]:
array = np.array([[ 1, -1,  2, -2,  3, -3],
                  [ 1, -1,  2, -2,  3, -3],
                  [ 1, -1,  2, -2,  3, -3]])

split_arrays = np.hsplit(array, [2])

print("split arrays:")
print_splits(split_arrays)

split arrays:
[[ 1 -1]
 [ 1 -1]
 [ 1 -1]] 

[[ 2 -2  3 -3]
 [ 2 -2  3 -3]
 [ 2 -2  3 -3]] 



In [ ]:
split_arrays = np.hsplit(array, [1, 2])

print("split arrays:")
print_splits(split_arrays)

split arrays:
[[1]
 [1]
 [1]] 

[[-1]
 [-1]
 [-1]] 

[[ 2 -2  3 -3]
 [ 2 -2  3 -3]
 [ 2 -2  3 -3]] 



### Split - Vertical

*   `np.vsplit(arr, indices_or_sections)`
  *   Splits the given `arr` into multiple sub-arrays vertically i.e row-wise and returns a list of sub-arrays.
  *   It is equivalent to split with `axis = 0`.
  * `.vsplit` only works on arrays of 2 or more dimensions.

In [ ]:
array = np.array([[1,   1,  1],
                  [-1, -1, -1],
                  [2,   2,  2],
                  [-2, -2, -2],
                  [3,   3,  3],
                  [-3, -3, -3]])

split_arrays = np.vsplit(array, [2])

print("split arrays:")
print_splits(split_arrays)

split arrays:
[[ 1  1  1]
 [-1 -1 -1]] 

[[ 2  2  2]
 [-2 -2 -2]
 [ 3  3  3]
 [-3 -3 -3]] 



In [ ]:
split_arrays = np.vsplit(array, [2,3])
print_splits(split_arrays)

[[ 1  1  1]
 [-1 -1 -1]] 

[[2 2 2]] 

[[-2 -2 -2]
 [ 3  3  3]
 [-3 -3 -3]] 



## Joining Arrays

### Concatenation of arrays



`np.concatenate((a1, a2, ...), axis=0)`
  *   Joins a sequence of arrays along the **given axis** and returns the concatenated array.
  *   The arrays must have the same shape, except in the dimension corresponding to the `axis`.
  *  The resulting array has the same dimensions as that of the input arrays.

In [ ]:
a = np.array([7, 1, 11])
b = np.array([3, 0, 17])

np.concatenate((a, b))

array([ 7,  1, 11,  3,  0, 17])

Concatenate along axis-0

In [ ]:
a = np.array([[7, 4, 5], 
              [1, 3, 2]])

b = np.array([[-1, -2, -3]])

np.concatenate((a, b), axis=0)

array([[ 7,  4,  5],
       [ 1,  3,  2],
       [-1, -2, -3]])

Concatenate along axis-1

In [ ]:
a = np.array([[7, 4, 5], 
              [1, 3, 2]])

b = np.array([[-1], 
             [-2]])

np.concatenate((a, b), axis=1)

array([[ 7,  4,  5, -1],
       [ 1,  3,  2, -2]])

The split arrays obtained by `np.split()` can be concatenated using `np.concatenate()` to get the original array.

In [ ]:
array = np.array([[1,   1,  1],
                  [-1, -1, -1],
                  [2,   2,  2],
                  [-2, -2, -2],
                  [3,   3,  3],
                  [-3, -3, -3]])

split_arrays = np.split(array, [2], axis=0)

print("split arrays:")
print_splits(split_arrays)

np.concatenate(split_arrays, axis=0)

split arrays:
[[ 1  1  1]
 [-1 -1 -1]] 

[[ 2  2  2]
 [-2 -2 -2]
 [ 3  3  3]
 [-3 -3 -3]] 



array([[ 1,  1,  1],
       [-1, -1, -1],
       [ 2,  2,  2],
       [-2, -2, -2],
       [ 3,  3,  3],
       [-3, -3, -3]])

### Stacking - Vertical




*   `np.vstack((a1, a2, ...))`
  *   Stacks the arrays a1, a2, … vertically (row-wise) in sequence and returns the stacked array.
  * Except in the case of 1D arrays, it's equivalent to `np.concatenate` along `axis = 0`



1-D arrays must have the same length to apply `np.vstack` on them

In [ ]:
a = np.array([1, 7, 11]) # 1D array
b = np.array([10, 20, 30])

vstack_array = np.vstack((a, b))
print(vstack_array)

[[ 1  7 11]
 [10 20 30]]


nD-arrays (n > 1) must have the same shape along every axis except for the first axis (axis-0).

In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([[-1,   -2,  -3], 
              [-4,   -5,  -6],
              [-7,   -8,  -9],
              [-10, -11, -12]])

np.vstack((a, b))

array([[  1,   2,   3],
       [  4,   5,   6],
       [ -1,  -2,  -3],
       [ -4,  -5,  -6],
       [ -7,  -8,  -9],
       [-10, -11, -12]])

### Stacking - Horizontal

* `np.hstack((a1, a2, ...))`
  *  Stacks the arrays a1, a2, … horizontally (column-wise) in sequence and returns the stacked array.
  *   Except in the case of 1D arrays, its equivalent to `np.concatenate` along axis = 1


1-D arrays can be of any length

In [ ]:
a = np.array([1, 7, 11]) 
b = np.array([10, 20])

np.hstack((a, b))

array([ 1,  7, 11, 10, 20])

nD-arrays (n > 1) must have the same shape along every axis except for the second axis (axis-1).

In [ ]:
a = np.array([[1, 2], 
             [3, 4],
             [5, 6]])

b = np.array([[-1,  -2,  -3,  -4], 
              [-5,  -6,  -7,  -8],
              [-9, -10, -11, -12]])

np.hstack((a, b))

array([[  1,   2,  -1,  -2,  -3,  -4],
       [  3,   4,  -5,  -6,  -7,  -8],
       [  5,   6,  -9, -10, -11, -12]])

### Stacking




*   `np.stack(arrays, axis=0)`
  *   Joins a sequence of arrays along the **new axis**.
  *   All input arrays must have the **same shape**.
  *   The resulting array has 1 additional dimension compared to the input arrays.
  *   The `axis` parameter specifies the index of the new axis which has to be created.



In [ ]:
a = np.array([1, 2, 3])
b = np.array([-1, -2, -3])

stacked_axis_0 = np.stack([a, b], axis = 0)
shape_axis_0 = stacked_axis_0.shape

print("stacked array with axis-0:\n", stacked_axis_0, "\n")

stacked_axis_1 = np.stack([a, b], axis = 1)
shape_axis_1 = stacked_axis_1.shape

print("stacked array with axis-1:\n", stacked_axis_1)

stacked array with axis-0:
 [[ 1  2  3]
 [-1 -2 -3]] 

stacked array with axis-1:
 [[ 1 -1]
 [ 2 -2]
 [ 3 -3]]


In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.array([[-1, -2, -3], 
              [-4, -5, -6]])

stacked_axis_2 = np.stack([a, b], axis = 2)
print("stacked array with axis-2:\n", stacked_axis_2, "\n")

print("shape of given arrays: ", a.shape)
print("shape of stacked array:", stacked_axis_2.shape)

stacked array with axis-2:
 [[[ 1 -1]
  [ 2 -2]
  [ 3 -3]]

 [[ 4 -4]
  [ 5 -5]
  [ 6 -6]]] 

shape of given arrays:  (2, 3)
shape of stacked array: (2, 3, 2)


**The size of the new dimension which is created will be equal to the number of arrays that are stacked**

In [ ]:
arrays = [np.random.randn(2, 3) for i in range(5)]

np.stack(arrays, axis=2).shape

(2, 3, 5)

## Tiling arrays


### np.repeat()


*   `numpy.repeat(arr, num_repeats, axis=None)`
  *   Repeats elements of an array.
  *   Outputs an array which has the same shape as `arr`, except along the given `axis`.
  *   `num_repeats` are the number of repetitions for each element which is broadcasted to fit the shape of the given axis.


In [ ]:
np.repeat(2, 5)

array([2, 2, 2, 2, 2])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

np.repeat(a, 2, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

**`num_repeats`** can also be a list that indicates how many times each of the corresponding elements should be repeated (along the given axis)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

np.repeat(a, [3,5], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

## Adding and removing elements


### np.delete()



*   `np.delete(arr, delete_indices, axis=None)`
  *   Returns a new array by deleting all the sub-arrays along the mentioned `axis`.
  *   `delete_indices` indicates the indices of the sub-arrays that need to be removed along the specified `axis`.






In [ ]:
a = np.array([[ 1,  3,  5,  7],
              [ 2,  4,  6,  8],
              [-1, -2, -3, -4]])

delete_in_axis_0 = np.delete(a, 1, 0)
print("delete at position-1 along axis-0:\n", delete_in_axis_0)

delete at position-1 along axis-0:
 [[ 1  3  5  7]
 [-1 -2 -3 -4]]


In [ ]:
a = np.array([[ 1,  3,  5,  7],
              [ 2,  4,  6,  8],
              [-1, -2, -3, -4]])

delete_in_axis_1 = np.delete(a, 2, 1)
print("delete at position-2 along axis-1:\n", delete_in_axis_1)

delete at position-2 along axis-1:
 [[ 1  3  7]
 [ 2  4  8]
 [-1 -2 -4]]


In [ ]:
a = np.array([[ 1,  3,  5,  7],
              [ 2,  4,  6,  8],
              [-1, -2, -3, -4]])

np.delete(a, [0,3], axis=None)

array([ 3,  5,  2,  4,  6,  8, -1, -2, -3, -4])

### np.insert()



*   `numpy.insert(arr, indices, values, axis=None)`
  *   Insert values along the given axis before the given indices.
  *   **indices** defines the index or indices before which the given `values` are inserted.
  *   **values** to insert into `arr`. If the type of values is different from that of `arr`, `values` is converted to the type of `arr`. values should be shaped so that `arr[...,indices,...] = values` is legal.
  *   Output is a copy of `arr` with values appended to the specified axis.





In [ ]:
a = np.array([[1, -1], 
              [2, -2], 
              [3, -3]])

insert_axis_0 = np.insert(a, 1, [4, 4], axis=0)
print("insert 4's at position-1 along axis-0:\n", insert_axis_0)

insert 4's at position-1 along axis-0:
 [[ 1 -1]
 [ 4  4]
 [ 2 -2]
 [ 3 -3]]


In [ ]:
insert_axis_1 = np.insert(a, 1, 4, axis=1)
print("insert 4's at position-1 along axis-1:\n",insert_axis_1)

insert 4's at position-1 along axis-1:
 [[ 1  4 -1]
 [ 2  4 -2]
 [ 3  4 -3]]


In [ ]:
a = np.array([[1, -1], 
              [2, -2], 
              [3, -3]])

zeros = np.zeros((3,2))

np.insert(a, [1], zeros, axis=1)

array([[ 1,  0,  0, -1],
       [ 2,  0,  0, -2],
       [ 3,  0,  0, -3]])

In [ ]:
a = np.array([[1, -1], 
              [2, -2], 
              [3, -3]])

np.insert(a, 1, 4, axis=None)

array([ 1,  4, -1,  2, -2,  3, -3])

### np.append()

*  `numpy.append(arr, values, axis=None)`
  *  Append values to the end of an array.
  *  Output is a copy of `arr` with values appended to axis.



*   If axis is given, both `arr` and `values` should have the same shape




In [ ]:
array_2d = np.array([[1, 2, 3], 
              [4, 5, 6]])

values = np.array([[-1, -2, -3], 
              [-4, -5, -6]])

np.append(array_2d, values, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-1, -2, -3],
       [-4, -5, -6]])

In [ ]:
np.append(array_2d, values, axis=1)

array([[ 1,  2,  3, -1, -2, -3],
       [ 4,  5,  6, -4, -5, -6]])

 

*   If `axis` is not given, both `arr` and `values` are flattened before use.

In [ ]:
np.append(array_2d, values)

array([ 1,  2,  3,  4,  5,  6, -1, -2, -3, -4, -5, -6])

## Padding

* `numpy.pad(array, pad_width, mode='constant', **kwargs)`
  * `pad_width` is the number of values padded to the edges of each axis.
  * Output is a padded array of rank equal to `array`, with shape increased according to `pad_width`. 


* `mode = ‘constant’` (default)

    * Pads with a constant value.

* `constant_values`: The padded values to set for each axis.


In [ ]:
array = np.array([[1, 3], [7, 9]])

pad_array_constant = np.pad(array, (1, 2), 'constant', constant_values=(-1, -2))
print('pad_array_constant:\n', pad_array_constant)

pad_array_constant:
 [[-1 -1 -1 -2 -2]
 [-1  1  3 -2 -2]
 [-1  7  9 -2 -2]
 [-1 -2 -2 -2 -2]
 [-1 -2 -2 -2 -2]]


* `mode = ‘edge’`
    * Pads with the edge values of the array.


In [ ]:
array = np.array([[1, 3], [7, 9]])

pad_array_edge = np.pad(array, (1, 1), 'edge')
print('pad_array_edge:\n', pad_array_edge)

pad_array_edge:
 [[1 1 3 3]
 [1 1 3 3]
 [7 7 9 9]
 [7 7 9 9]]


## Understanding NumPy Internals

In [ ]:
import numpy as np

original_3D = np.array([[['A', 'B'],
                      ['C', 'D'],
                      ['E', 'F']],
                     
                     [['G', 'H'],
                      ['I', 'J'],
                      ['K', 'L']],
                     
                     [['M', 'N'],
                      ['O', 'P'],
                      ['Q', 'R']],
                     
                     [['S', 'T'],
                      ['U', 'V'],
                      ['W', 'X']]])

print("original_3D shape: ", original_3D.shape)
print("original_3D strides: ", original_3D.strides)
print("original_3D data: ", original_3D.data, "\n")

print(original_3D, "\n")

original_3D shape:  (4, 3, 2)
original_3D strides:  (24, 8, 4)
original_3D data:  <memory at 0x7f972434e8b8> 

[[['A' 'B']
  ['C' 'D']
  ['E' 'F']]

 [['G' 'H']
  ['I' 'J']
  ['K' 'L']]

 [['M' 'N']
  ['O' 'P']
  ['Q' 'R']]

 [['S' 'T']
  ['U' 'V']
  ['W' 'X']]] 



#### **`np.ravel`**

In [ ]:
ravel_3D = original_3D.ravel()

print("ravel_3D shape: ", ravel_3D.shape)
print("ravel_3D strides: ", ravel_3D.strides)
print(ravel_3D.base is original_3D)

ravel_3D shape:  (24,)
ravel_3D strides:  (4,)
True


#### **`np.swapaxes`**

In [ ]:
swap_3D = np.swapaxes(original_3D, 1, 2)

print("swap_3D shape: ", swap_3D.shape)
print("swap_3D strides: ", swap_3D.strides)
print(swap_3D.base is original_3D)

swap_3D shape:  (4, 2, 3)
swap_3D strides:  (24, 4, 8)
True


#### **`np.moveaxis`**

In [ ]:
move_3D = np.moveaxis(original_3D, [1],[2])

print("move_3D shape: ", move_3D.shape)
print("move_3D strides: ", move_3D.strides)
print(move_3D.base is original_3D)

move_3D shape:  (4, 2, 3)
move_3D strides:  (24, 4, 8)
True


In [ ]:
print(move_3D, "\n")
print(move_3D[0,0,0])
print(move_3D[0,0,1])

[[['A' 'C' 'E']
  ['B' 'D' 'F']]

 [['G' 'I' 'K']
  ['H' 'J' 'L']]

 [['M' 'O' 'Q']
  ['N' 'P' 'R']]

 [['S' 'U' 'W']
  ['T' 'V' 'X']]] 

A
C


#### **`np.reshape`**

In [ ]:
reshape_3D = np.reshape(original_3D, (4, 2, 3))

print("reshape_3D shape: ", reshape_3D.shape)
print("reshape_3D strides: ", reshape_3D.strides)
print(reshape_3D.base is original_3D)

reshape_3D shape:  (4, 2, 3)
reshape_3D strides:  (24, 12, 4)
True


In [ ]:
print(reshape_3D, "\n")
print(reshape_3D[0,0,0])
print(reshape_3D[0,0,1])

[[['A' 'B' 'C']
  ['D' 'E' 'F']]

 [['G' 'H' 'I']
  ['J' 'K' 'L']]

 [['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']]] 

A
B


#### **Slicing**

In [ ]:
sliced_3D = original_3D[::2,:,::2]

print("sliced_3D shape: ", sliced_3D.shape)
print("sliced_3D strides: ", sliced_3D.strides)
print("sliced_3D data: ", sliced_3D.data, "\n")

print(sliced_3D.base is original_3D)

sliced_3D shape:  (2, 3, 1)
sliced_3D strides:  (48, 8, 8)
sliced_3D data:  <memory at 0x7f972434e8b8> 

True


#### **`np.transpose`**

In [ ]:
transpose_3D = original_3D.T

print("transpose_3D shape: ", transpose_3D.shape)
print("transpose_3D strides: ", transpose_3D.strides)
print(transpose_3D.base is original_3D)

transpose_3D shape:  (2, 3, 4)
transpose_3D strides:  (4, 8, 24)
True


For more details, look at 
*  https://numpy.org/doc/stable/reference/internals.html
*  https://ipython-books.github.io/45-understanding-the-internals-of-numpy-to-avoid-unnecessary-array-copying/