<a href="https://colab.research.google.com/github/nike-2001/AI-Hands-on/blob/main/Copy_of_Array_Operations_%26_Ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing numpy
import numpy as np

# Operations on Numpy Arrays


### Adding Numpy Arrays vs Python Lists


In Python, adding two Python Lists will create a new list that contains elements from both the lists in the given order **(List Concatenation)**.


In [ ]:
concatented_list = [1, 5, 1, 0, 7] + [2, 4, 3, 1, 3]
print("Concatenated List: ", concatented_list)

Concatenated List:  [1, 5, 1, 0, 7, 2, 4, 3, 1, 3]


But, when we add two NumPy Arrays, elements of one array will be added to the corresponding elements in the other array **(Vectorized Addition)**

In [ ]:
sum_of_two_arrays = np.array([1, 5, 13, 0, 7]) + np.array([2, 4, 8, 7, 13]) 
print("Sum of two arrays: ", sum_of_two_arrays)

Sum of two arrays:  [ 3  9 21  7 20]


### Operator Overloading

In [ ]:
a = np.array([1, 5, 1, 0, 7])
b = np.array([2, 4, 3, 1, 3])

sum_a_b = np.add(a, b)
print("sum of two arrays with add function: ", sum_a_b)

sum of two arrays with add function:  [ 3  9  4  1 10]


In [ ]:
sum_with_operator = a + b
print("sum of two arrays with + operator: ", sum_with_operator)

sum of two arrays with + operator:  [ 3  9  4  1 10]


### Vectorized Operations with NumPy

In [ ]:
vec_size = 1000
a = np.arange(vec_size)
b = np.arange(vec_size)

In [ ]:
def addition_with_loop():
    sum_a_b = [a[i] + b[i] for i in range(len(a))]
    return sum_a_b

In [ ]:
def vectorized_np_addition():
    sum_a_b = a + b
    return sum_a_b

In [ ]:
%timeit addition_with_loop()

1000 loops, best of 3: 389 µs per loop


In [ ]:
%timeit vectorized_np_addition()

The slowest run took 38.37 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.14 µs per loop


* As we have seen with addition, many other operators also support Vectorized Operations (we can apply element-wise operations without having to iterate over all the elements individually)

* This enables us to do a lot of computations much faster and with less code.

## Array Operations

### Arithmetic Operations

| Arithmetic Operation | Numpy Function | Python Operator |
| :---------------: | :---------------: | :---------------: |
|  Addition  | 		np.add | + |
|  Subtraction | np.subtract | - |
|  Multiplication  | 	np.multiply | * |
|  Division | 	np.divide | / |
|  Integer Division | 	np.floor_divide | // |
|  Modulo Operation | 	np.mod | % |
|  	Power | np.power | ** |


 

In [ ]:
a = np.array([1, 5, 1, 0, 7])
b = np.array([2, 4, 3, 1, 3])

difference = np.subtract(a, b)
print("difference: ", difference)

product = np.multiply(a, b)
print("product: ", product)

division = np.divide(a, b)
print("division: ", division)

floor_division = np.floor_divide(a, b)
print("floor_division: ", floor_division)

remainder = np.mod(a, b)
print("remainder: ", remainder)

a_power_b_with_function = np.power(a, b)
print("a_power_b_with_function: ", a_power_b_with_function)

a_power_b_with_operator = a**b
print("a_power_b_with_operator: ", a_power_b_with_operator)

difference:  [-1  1 -2 -1  4]
product:  [ 2 20  3  0 21]
division:  [0.5        1.25       0.33333333 0.         2.33333333]
floor_division:  [0 1 0 0 2]
remainder:  [1 1 1 0 1]
a_power_b_with_function:  [  1 625   1   0 343]
a_power_b_with_operator:  [  1 625   1   0 343]


### Relational Operations


 | Relational Operation | Numpy Function | Python Operator |
| :---------------: | :---------------: | :---------------: |
|  Greater Than  | 		np.greater | > |
|  Greater Than Equal | np.greater_equal | >= |
|  Less Than  | 	np.less | < |
|  Less Than Equal | 	np.less_equal | <= |
|  Equal | 	np.equal | == |
|  Not Equal | 	np.not_equal	 | != |




*   Relational Operations return Boolean Arrays



In [ ]:
a = np.array([1, 5, 1, 0, 7])
b = np.array([2, 4, 3, 1, 3])

print("np.greater(a, b):", np.greater(a, b))
print("           a > b:", a > b, "\n")

print("np.greater_equal(a, b):", np.greater_equal(a, b))
print("                a >= b:", a >= b, "\n")

print("np.less(a, b):", np.less(a, b))
print("        a < b:", a < b, "\n")

print("np.less_equal(a, b):", np.less_equal(a, b))
print("             a <= b:", a <= b, "\n")

print("np.equal(a, b):", np.equal(a, b))
print("        a == b:", a == b, "\n")

print("np.not_equal(a, b):", np.not_equal(a, b))
print("            a != b:", a != b)

np.greater(a, b): [False  True False False  True]
           a > b: [False  True False False  True] 

np.greater_equal(a, b): [False  True False False  True]
                a >= b: [False  True False False  True] 

np.less(a, b): [ True False  True  True False]
        a < b: [ True False  True  True False] 

np.less_equal(a, b): [ True False  True  True False]
             a <= b: [ True False  True  True False] 

np.equal(a, b): [False False False False False]
        a == b: [False False False False False] 

np.not_equal(a, b): [ True  True  True  True  True]
            a != b: [ True  True  True  True  True]


### Bitwise Operations

 | Bitwise Operation | Numpy Function | Python Operator |
| :---------------: | :---------------: | :---------------: |
|  Bitwise AND  | 		np.bitwise_and | & |
|  Bitwise OR | np.bitwise_or | \| |
|  Bitwise XOR  | 	np.bitwise_xor | ^ |
|  Bitwise NOT | 	np.invert | ~ |
|  Left Shift | 	np.left_shift | << |
|  Right Shift | 	np.right_shift | >> |


 
 
 
 

In [ ]:
a = np.array([1, 0, 1, 0, 1])
b = np.array([1, 0, 0, 1, 1])
print("np.bitwise_and(a, b):", np.bitwise_and(a, b))
print("               a & b:", a & b)

np.bitwise_and(a, b): [1 0 0 0 1]
               a & b: [1 0 0 0 1]


In [ ]:
print("np.bitwise_or(a, b):", np.bitwise_or(a, b))
print("              a | b:", a | b, "\n")

print("np.bitwise_xor(a, b):", np.bitwise_xor(a, b))
print("               a ^ b:", a ^ b, "\n")

print("np.invert(a):", np.invert(a))
print("          ~a:", ~a, "\n")

print("np.left_shift(a, b):", np.left_shift(a, b))
print("             a << b:", a << b, "\n")

print("np.right_shift(a, b):", np.right_shift(a, b))
print("              a >> b:", a >> b, "\n")

np.bitwise_or(a, b): [1 0 1 1 1]
              a | b: [1 0 1 1 1] 

np.bitwise_xor(a, b): [0 0 1 1 0]
               a ^ b: [0 0 1 1 0] 

np.invert(a): [-2 -1 -2 -1 -2]
          ~a: [-2 -1 -2 -1 -2] 

np.left_shift(a, b): [2 0 1 0 2]
             a << b: [2 0 1 0 2] 

np.right_shift(a, b): [0 0 1 0 0]
              a >> b: [0 0 1 0 0] 



### Operations on 2D Arrays
All the arithmetic, relational and bitwise operations can be done on 2D, 3D arrays and in general on nD arrays as well.

In [ ]:
a = np.array([[1,3,2],
              [0,2,-1]])

b = np.array([[1,1,1],
              [2,2,2]])

print("a + b:\n", a + b, "\n")
print("a > b:\n", a > b)

a + b:
 [[2 4 3]
 [2 4 1]] 

a > b:
 [[False  True  True]
 [False False False]]


## Linear Algebra

### `numpy.matmul`

The `matmul` function implements the semantics of the `@` operator introduced in Python 3.5.

In [ ]:
a = np.array([[3, 1, 2], 
              [4, 2, 1]])

b = np.array([[2, 3], 
              [-1, 0], 
              [-3, 4]])

print("shape of a:", a.shape)
print("shape of b:", b.shape, "\n")

print("np.matmul(a, b):\n", np.matmul(a, b), "\n")
print("a @ b :\n", a @ b)

shape of a: (2, 3)
shape of b: (3, 2) 

np.matmul(a, b):
 [[-1 17]
 [ 3 16]] 

a @ b :
 [[-1 17]
 [ 3 16]]


**`matmul` in the case of Rank 1 Arrays**

In [ ]:
a = np.array([3, 1, 2, 4])
b = np.array([5, 2, 0, 1])

print("shape of a:", a.shape)
print("shape of b:", b.shape, "\n")

print("np.matmul(a, b):\n", np.matmul(a, b), "\n")
print("a @ b :\n", a @ b, "\n \n")

print("np.matmul(b, a):\n", np.matmul(b, a), "\n")
print("b @ a :\n", b @ a)

shape of a: (4,)
shape of b: (4,) 

np.matmul(a, b):
 21 

a @ b :
 21 
 

np.matmul(b, a):
 21 

b @ a :
 21


### Reshaping Rank-1 Arrays

In [ ]:
a = np.array([3, 1, 2, 4])
b = np.array([5, 2, 0, 1])

print("shape of a:", a.shape)
print("shape of b:", b.shape, "\n")

a = a.reshape(1, 4)
b = b.reshape(4, 1)

print("np.matmul(a, b):\n", np.matmul(a, b), "\n")
print("a @ b :\n", a @ b, "\n \n")

print("np.matmul(b, a):\n", np.matmul(b, a), "\n")
print("b @ a :\n", b @ a)

shape of a: (4,)
shape of b: (4,) 

np.matmul(a, b):
 [[21]] 

a @ b :
 [[21]] 
 

np.matmul(b, a):
 [[15  5 10 20]
 [ 6  2  4  8]
 [ 0  0  0  0]
 [ 3  1  2  4]] 

b @ a :
 [[15  5 10 20]
 [ 6  2  4  8]
 [ 0  0  0  0]
 [ 3  1  2  4]]


### Transpose of an array

In [ ]:
a = np.array([[3, 1, 2], 
              [4, 2, 1]])

np.transpose(a)

array([[3, 4],
       [1, 2],
       [2, 1]])

Can also use **`a.T`** to transpose an array

In [ ]:
a = np.array([[3, 1, 2], 
              [4, 2, 1]])

a.T

array([[3, 4],
       [1, 2],
       [2, 1]])

**Transposing Rank 1 arrays**

In [ ]:
a = np.array([3, 1, 4, -2]).reshape(1, 4)
print("Array before transposing: \n", a)

b = np.transpose(a)
print("Array after transposing: \n", b)

Array before transposing: 
 [[ 3  1  4 -2]]
Array after transposing: 
 [[ 3]
 [ 1]
 [ 4]
 [-2]]


In [ ]:
a = np.array([3, 1, 4, -2])
print("Rank 1 Array before transposing: \n", a)

b = np.transpose(a)
print("Rank 1 Array after transposing: \n", b)

Rank 1 Array before transposing: 
 [ 3  1  4 -2]
Rank 1 Array after transposing: 
 [ 3  1  4 -2]


### Other linear algebra functions
[NumPy `linalg` Documentation](https://numpy.org/doc/stable/reference/routines.linalg.html)

Determinant of an array

In [ ]:
a = np.array([[1, 2], 
              [1, 3]])

determinant = np.linalg.det(a)
print("Determinant of array:", determinant)

Determinant of array: 1.0


Multiplicative inverse of a matrix

In [ ]:
a = np.array([[1, 2], 
              [1, 3]])

inverse = np.linalg.inv(a)
print("Inverse of array:\n", inverse)

Inverse of array:
 [[ 3. -2.]
 [-1.  1.]]


# Broadcasting

Broadcasting two arrays together follows these rules:

*  Two arrays are said to be compatible in a dimension if 
 * they have the same size in that dimension, or 
 * one of the arrays has size 1 in that dimension.
*   The arrays can be broadcast together if they are compatible in all dimensions.
*   After broadcasting, each array behaves as if its shape is equal to the element-wise maximum of the shapes of the two input arrays.
*   In any dimension where one array has a size of 1 and the other array has a size greater than 1, the first array behaves as if it were copied along that dimension.


In [ ]:
a = np.zeros((3, 4))
b = np.array([1, 2 ,3, -1])

print("a:\n", a, "\n")
print("b:\n", b, "\n")
print("a + b:\n", a + b)

a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

b:
 [ 1  2  3 -1] 

a + b:
 [[ 1.  2.  3. -1.]
 [ 1.  2.  3. -1.]
 [ 1.  2.  3. -1.]]


In [ ]:
a = np.zeros((3,4))
b = np.array([[1], 
              [2], 
              [3]])

print("a:\n", a, "\n")
print("b:\n", b, "\n")
print("a + b:\n", a + b)

a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

b:
 [[1]
 [2]
 [3]] 

a + b:
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [ ]:
a = np.zeros((3,4))

print("a:\n", a, "\n")
print("a + b:\n", a + 5)

a:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

a + b:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [ ]:
a = np.array([[3, 1, 2, -1],
             [4, 2, 1, 0],
             [-2, 1, 3, 4]])

b = np.array([1, 0, 2, 1])

print("a:\n", a, "\n")
print("b:\n", b, "\n")
print("a + b:\n", a + b)

a:
 [[ 3  1  2 -1]
 [ 4  2  1  0]
 [-2  1  3  4]] 

b:
 [1 0 2 1] 

a + b:
 [[ 4  1  4  0]
 [ 5  2  3  1]
 [-1  1  5  5]]


### Broadcasting and Masking

In [ ]:
A = np.array([[3, 4, 1, 2],
              [0, -1, 7, 9]])

mask = A > 3
print("mask created with broadcasting: \n", mask, "\n")

print("applying the mask on A: \n", A[mask])

mask created with broadcasting: 
 [[False  True False False]
 [False False  True  True]] 

applying the mask on A: 
 [4 7 9]


# Other Useful Methods in NumPy

**A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features.**

**There are currently more than 60 universal functions defined in numpy on one or more types, covering a wide variety of operations.**

You can find the list of ufuncs in this [documentation](https://numpy.org/doc/stable/reference/ufuncs.html).

### Sum of the elements of array


*   `np.sum(a, axis=None)`
*   `ndarray.sum(axis=None)`
  *   Returns the sum of array elements along the given axis. If axis is None, then it computes the sum of all the elements in the array.

In [ ]:
array_1d = np.array([1, 2, 3])

print("sum of all elements:", np.sum(array_1d))
print("sum of all elements alternative:", array_1d.sum())

sum of all elements: 6
sum of all elements alternative: 6


In [ ]:
array_2d = np.array([[1, 2, 1], 
                    [-1, 0, 3]])

array_2d_sum = array_2d.sum()
print("sum of all elements:", array_2d_sum)

sum of all elements: 6


**Sum along different axes**

In [ ]:
sum_axis_0 = array_2d.sum(axis = 0)

print("array_2d:\n", array_2d, "\n")
print("sum along axis 0:", sum_axis_0)

array_2d:
 [[ 1  2  1]
 [-1  0  3]] 

sum along axis 0: [0 2 4]


In [ ]:
sum_axis_1 = array_2d.sum(axis = 1)

print("array_2d:\n", array_2d, "\n")
print("sum along axis 1:", sum_axis_1)

array_2d:
 [[ 1  2  1]
 [-1  0  3]] 

sum along axis 1: [4 2]


**Sum in 3D arrays**

In [ ]:
array_3d = np.array([[[ 1,  0],
                      [ 2,  3],
                      [ 1,  4],
                      [-1,  2]],

                     [[-1,  0],
                      [ 1,  4],
                      [ 1,  2],
                      [ 3, -1]],

                    [[-4,  1],
                     [ 2,  0],
                     [ 1,  2],
                     [ 0,  1]]])

In [ ]:
print("array_3d:\n", array_3d, "\n")

print("sum of all elements in array_3d:", array_3d.sum(), "\n")
print("sum along axis 0:\n", array_3d.sum(axis = 0), "\n")
print("sum along axis 1:\n", array_3d.sum(axis = 1), "\n")
print("sum along axis 2:\n", array_3d.sum(axis = 2))

array_3d:
 [[[ 1  0]
  [ 2  3]
  [ 1  4]
  [-1  2]]

 [[-1  0]
  [ 1  4]
  [ 1  2]
  [ 3 -1]]

 [[-4  1]
  [ 2  0]
  [ 1  2]
  [ 0  1]]] 

sum of all elements in array_3d: 24 

sum along axis 0:
 [[-4  1]
 [ 5  7]
 [ 3  8]
 [ 2  2]] 

sum along axis 1:
 [[ 3  9]
 [ 4  5]
 [-1  4]] 

sum along axis 2:
 [[ 1  5  5  1]
 [-1  5  3  2]
 [-3  2  3  1]]


### `np.add.reduce()`

*   `np.add.reduce()` is equivalent to `np.sum()`.
*   `np.sum()` internally calls `np.add.reduce`

In [ ]:
array_2d = np.array([[1, 2, 1], 
                    [-1, 0, 3]])

sum_1 = np.sum(array_2d, axis = 0)
print("using np.sum:", sum_1)

sum_2 = np.add.reduce(array_2d, axis = 0)
print("using np.add.reduce:", sum_2)

using np.sum: [0 2 4]
using np.add.reduce: [0 2 4]


### Maximum of the elements in an array

In [ ]:
array_2d = np.array([[1, 2, 1], 
                    [-1, 0, 3]])

max_of_array = array_2d.max()
print("max of array:", max_of_array)

max_of_array = np.max(array_2d)
print("max of array alternative:", max_of_array)

max_axis_0 = array_2d.max(axis=0)
print("max along axis 0:", max_axis_0)

max_axis_1 = array_2d.max(axis=1)
print("max along axis 1:", max_axis_1)


max of array: 3
max of array alternative: 3
max along axis 0: [1 2 3]
max along axis 1: [2 3]


In [ ]:
array_2d = np.array([[1, 2, 1], 
                    [-1, 0, 3]])


sum_2 = np.maximum.reduce(array_2d, axis = 0)
print("using np.maximum.reduce:", sum_2)

using np.maximum.reduce: [1 2 3]


**Argmax**

In [ ]:
array_1d = np.array([1, -1, 3, 0, 2])

print("maximum element:", np.max(array_1d))
print("maximum element is at index:", np.argmax(array_1d))

maximum element: 3
maximum element is at index: 2


### Sorting

#### In-place sorting vs New sorted array

`np.sort()` returns a sorted copy of an array

In [ ]:
array_1d = np.array([1, -1, 3, 0, 2])

sorted_array = np.sort(array_1d)

print("array_1d:", array_1d)
print("sorted array:", sorted_array)

array_1d: [ 1 -1  3  0  2]
sorted array: [-1  0  1  2  3]


`ndarray.sort()` sorts an array in-place

In [ ]:
array_1d = np.array([1, -1, 3, 0, 2])

array_1d.sort()
print("array_1d:", array_1d)

array_1d: [-1  0  1  2  3]


#### `np.argsort()`
 returns the indices that would sort an array.

In [ ]:
array_1d = np.array([1, -1, 3, 0, 2])

indices = np.argsort(array_1d)
print("indices that would sort array_1d:", indices)

indices that would sort array_1d: [1 3 0 4 2]


In [ ]:
print("Using fancy indexing with argsort:", array_1d[indices])

Using fancy indexing with argsort: [-1  0  1  2  3]


### Other math functions

[Link to documentation](https://numpy.org/doc/stable/reference/routines.math.html) 